### ISSUE TITLE
ARM/AMD Windows install of latest version triggers windows malware detection.

### ISSUE THREAD

**Issue by Colton1070** [lippkg/lip#105]
### Describe the bug

Title.

### To Reproduce

Use Windows. Install/extract latest release. Try to run.

### Expected behavior

Windows does not trigger "this file is a virus".

**Comment by futrime** [comment]
Not a bug. Lip lacks a signature trusted by Microsoft. If you have any idea to solve this problem, please help us.

**Comment by Colton1070** [comment]
Against my better judgement I disabled all of the windows security/virus protection to run the file and...

Nothing happens. A CMD prompt opens and immediately closes. Not sure how to make this work from here.

**Comment by futrime** [comment]
Indeed, Lip is a CLI tool. To begin your journey with Lip, simply open the shell and navigate to the directory where the lip.exe file is located. Once there, execute the command `lip.exe -h` to uncover information on how to effectively utilize Lip's functionalities.
