### ISSUE TITLE
有无可能提供原生的增量安装能力

### ISSUE THREAD

**Issue by yqs112358** [lippkg/lip#84]
例如，在更新BDS服务端时，使用某开关，则会对比两个版本的文件差异并仅进行增量安装（部分文件如server.properties甚至可以对比到行），这样不影响服务端中其他已安装的包
仅举个例子，不代表BDS就一定需要增量安装，可能有其他部分组件有此需求，有待深入讨论

**Comment by Futrime** [comment]
goproxy的机制使得最终还是得下载完整包诶

**Comment by harry-xi** [comment]
> goproxy的机制使得最终还是得下载完整包诶

"这样不影响服务端中其他已安装的包"
重点在这里，这能带来很多好处和便利。

**Comment by futrime** [comment]
加了preserve参数，也许算是一个实现
