### ISSUE TITLE
为tooth.json的placement提供通配符/正则匹配能力

### ISSUE THREAD

**Issue by yqs112358** [LipPkg/Lip#86]
目前对于根目录文件较多的情况，placement可能写得很长。希望可以简化这个机制，提供通配符/正则匹配能力

比较简单的实现可以参考.gitignore，比如
hello/**/a.txt
test/*.doc
mine/bds??-??-*.zip
directory/*
*
等等情况

不过由于通配符难以实现全选排除等效果，可以考虑正则实现完整匹配能力

**Comment by Futrime** [comment]
Now Lip supports pattern `abc/*` to match all directory structures under abc.
