### ISSUE TITLE
在安装来源非Tooth-Hub的包时输出免责声明

### ISSUE THREAD

**Issue by ShrBox** [LipPkg/Lip#87]
**Describe the solution you'd like**

当用户安装的包不是来自Tooth-Hub时，在控制台输出免责声明  
```
You are trying installing unofficial tooth package, we are not responsible for it.
```
参考Windows的winget

**Comment by Futrime** [comment]
不如安装所有包都输出免责声明

**Comment by ShrBox** [comment]
> 不如安装所有包都输出免责声明

主要是考虑到可能会有人在registry上面发布恶意软件（先提交正常的插件，通过之后再在插件的二进制文件动手脚）

**Comment by Futrime** [comment]
Now Lip is deprecating the interactions with the registry. Therefore, this issue is no longer an issue.
